-- ============================================================
-- Migration: Add speaking_prompts and practice_history tables
-- Run this in Supabase SQL Editor
-- ============================================================

-- Speaking Prompts (100 prompts: 20 per part)
CREATE TABLE IF NOT EXISTS speaking_prompts (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  part_number INTEGER NOT NULL CHECK (part_number BETWEEN 1 AND 5),
  task_type VARCHAR(50) NOT NULL,
  title VARCHAR(255) NOT NULL,
  passage TEXT,
  prompt TEXT NOT NULL,
  image_url VARCHAR(500),
  prep_seconds INTEGER DEFAULT 10,
  model_answer TEXT,
  hint_words TEXT[],
  order_index INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_speaking_prompts_part ON speaking_prompts(part_number);
CREATE INDEX IF NOT EXISTS idx_speaking_prompts_order ON speaking_prompts(part_number, order_index);

-- Practice History (all speaking/writing practice attempts)
CREATE TABLE IF NOT EXISTS practice_history (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  mode VARCHAR(20) NOT NULL CHECK (mode IN ('speaking', 'writing')),
  part_number INTEGER NOT NULL,
  prompt_id VARCHAR(100) NOT NULL,
  prompt_title VARCHAR(255) NOT NULL,
  prompt_content TEXT NOT NULL,
  user_answer TEXT NOT NULL DEFAULT '',
  ai_score INTEGER,
  ai_feedback TEXT,
  ai_errors TEXT[],
  ai_task_scores JSONB,
  ai_important_words TEXT[],
  ai_suggested_answer TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_practice_history_user ON practice_history(user_id);
CREATE INDEX IF NOT EXISTS idx_practice_history_mode ON practice_history(user_id, mode);
CREATE INDEX IF NOT EXISTS idx_practice_history_created ON practice_history(created_at DESC);

-- ============================================================
-- Seed: speaking_prompts (100 prompts: 20 per part)
-- ============================================================

-- Part 1: Read Aloud
INSERT INTO speaking_prompts (part_number, task_type, title, passage, prompt, order_index) VALUES
(1, 'read_aloud', 'Company Announcement', E'Good morning, everyone. I would like to thank you all for coming today. Our company has achieved remarkable growth over the past year, and we owe much of our success to the hard work and dedication of every team member here. Starting next month, we will be launching a new customer support portal designed to improve response time and enhance service quality. Please make sure to review the training materials that will be sent to your email by Friday. If you have any questions, feel free to reach out to the HR department. Thank you.', 'Read the passage aloud with clear pronunciation and natural pacing.', 1),
(1, 'read_aloud', 'Quarterly Sales Report', E'Our quarterly sales report shows a fifteen percent increase compared to the same period last year. The marketing team launched three successful campaigns across social media platforms, reaching over two million users in the Asia-Pacific region. Customer satisfaction ratings have improved significantly, with an average score of 4.6 out of 5. Looking ahead, we plan to expand into European markets by the end of next quarter. Full details are available in the document shared earlier this week.', 'Read the passage aloud with clear pronunciation and natural pacing.', 2),
(1, 'read_aloud', 'New Office Policy', E'As of next Monday, all employees will be required to use the new electronic access system to enter the building. Please make sure your employee badge is activated before Friday. If you experience any issues with the new system, contact the IT support desk on the second floor. The security office reminds everyone not to hold doors for strangers and to report any suspicious activity immediately. These measures are designed to ensure the safety of all staff members.', 'Read the passage aloud with clear pronunciation and natural pacing.', 3),
(1, 'read_aloud', 'Training Workshop Notice', E'Dear colleagues, we are pleased to announce a professional development workshop on effective communication skills. The workshop will be held in Conference Room B on March 15th from 9 AM to 4 PM. Participants will learn practical techniques for presenting ideas clearly, handling difficult conversations, and building stronger team relationships. Lunch and refreshments will be provided. Please register through the company portal by March 10th. Certificates of completion will be awarded to all participants.', 'Read the passage aloud with clear pronunciation and natural pacing.', 4),
(1, 'read_aloud', 'Project Update Email', E'I am writing to update you on the progress of the website redesign project. The design team has completed the mockups for all major pages, and the development team is currently working on the homepage and product catalog sections. We are on track to launch the beta version by the end of this month. Please review the attached documents and provide your feedback by Thursday. We value your input and want to ensure the final product meets everyone expectations.', 'Read the passage aloud with clear pronunciation and natural pacing.', 5),
(1, 'read_aloud', 'Health and Safety Reminder', E'Please be reminded that all visitors must sign in at the reception desk before accessing any area of the building. Fire evacuation drills will take place on the last Friday of each month at 2 PM. Please familiarize yourself with the nearest emergency exit and the designated assembly point in the parking lot. First aid kits are located in every break room and the main corridor near the elevator. Report any safety concerns to the facilities manager immediately.', 'Read the passage aloud with clear pronunciation and natural pacing.', 6),
(1, 'read_aloud', 'Team Building Event', E'We are excited to announce that this years team building event will take place at Green Lake Resort on June 20th. The day will include outdoor activities such as hiking, kayaking, and a friendly sports tournament. Transportation will be provided from the office at 8 AM. Participants should bring comfortable clothing, sunscreen, and a spirit of adventure. A BBQ lunch and evening dinner will be served on-site. Family members are welcome to join for the evening celebration. RSVP by June 1st.', 'Read the passage aloud with clear pronunciation and natural pacing.', 7),
(1, 'read_aloud', 'Budget Approval Notice', E'After careful review of all submitted proposals, the budget committee has approved the marketing campaign for the second quarter. The total allocated budget is $150,000, which will be distributed across digital advertising, influencer partnerships, and event sponsorship. Project managers must submit detailed spending plans by the end of this week. Monthly expense reports are required for all projects exceeding $10,000. Receipts must be submitted within five business days of each purchase.', 'Read the passage aloud with clear pronunciation and natural pacing.', 8),
(1, 'read_aloud', 'Performance Review Guidelines', E'The annual performance review season begins next month. All employees are required to complete a self-assessment form available on the HR portal by November 15th. Managers should schedule one-on-one meetings with their team members by December 1st to discuss achievements, areas for improvement, and career development goals. The new performance rating scale uses five levels: Exceptional, Exceeds Expectations, Meets Expectations, Needs Improvement, and Unsatisfactory. Training sessions on giving constructive feedback are available throughout October.', 'Read the passage aloud with clear pronunciation and natural pacing.', 9),
(1, 'read_aloud', 'Parking Lot Expansion', E'Due to increased staff numbers, the company has approved the expansion of the main parking lot. Construction will begin on January 8th and is expected to be completed by the end of February. During construction, temporary overflow parking will be available at the adjacent lot across the street. Carpooling is strongly encouraged during this period. Shuttle service from the overflow lot to the main entrance will run every fifteen minutes from 7 AM to 6 PM. We apologize for any inconvenience this may cause.', 'Read the passage aloud with clear pronunciation and natural pacing.', 10),
(1, 'read_aloud', 'Software License Renewal', E'This is a reminder that the annual license for our project management software expires on December 31st. The IT department has already negotiated a 15% discount for early renewal. To proceed with the renewal, each department head must confirm the number of user licenses needed by November 30th. New features included in this years update are an improved dashboard, better integration with third-party tools, and enhanced mobile access. Please contact the IT help desk if you have any questions.', 'Read the passage aloud with clear pronunciation and natural pacing.', 11),
(1, 'read_aloud', 'Customer Feedback Summary', E'Thank you to all customers who participated in our recent satisfaction survey. We received over 5,000 responses representing a 30% increase from last year. Key findings show that 87% of customers are satisfied with our product quality, while delivery speed remains our biggest area for improvement. We are committed to reducing average delivery time from five days to three days by next quarter. Your feedback directly shapes our improvement plans, and we will share our action items in the next newsletter.', 'Read the passage aloud with clear pronunciation and natural pacing.', 12),
(1, 'read_aloud', 'Holiday Schedule', E'Please note the upcoming office closures for the holiday season. The office will be closed from December 23rd through January 2nd. Emergency support lines will remain active throughout the holiday period. Employees who wish to work remotely during the closure must submit a request to their manager by December 15th. The holiday gift exchange will take place on December 20th at 3 PM in the main conference room. We wish everyone a wonderful and safe holiday season.', 'Read the passage aloud with clear pronunciation and natural pacing.', 13),
(1, 'read_aloud', 'Recycling Program Launch', E'Starting this week, our office is launching a comprehensive recycling program. Recycling bins will be placed next to every trash bin in all common areas and individual workspaces. Please separate paper, plastic, and organic waste as indicated on each bin. Electronics and batteries should be taken to the designated drop-off point near the loading dock. The facilities team will collect statistics on recycling participation and share monthly reports with all staff. Together, we aim to reduce our environmental footprint by 40% this year.', 'Read the passage aloud with clear pronunciation and natural pacing.', 14),
(1, 'read_aloud', 'New Product Launch', E'We are thrilled to announce the launch of our newest product line, EcoClean, which uses 100% biodegradable materials. The product will be available in stores nationwide starting April 22nd, coinciding with Earth Day. Pre-orders are already open on our website and have exceeded our target of 10,000 units. The marketing team has prepared a full launch plan including television ads, social media campaigns, and in-store demonstrations. Sales training sessions for retail partners will begin next week.', 'Read the passage aloud with clear pronunciation and natural pacing.', 15),
(1, 'read_aloud', 'Cafeteria Menu Change', E'Effective immediately, the cafeteria will offer an expanded vegetarian menu every Tuesday and Thursday. We have partnered with local organic farms to source fresh seasonal ingredients. The lunch buffet price remains unchanged at $8.50, which includes a main dish, two side items, and a beverage. A new salad bar with over twenty topping options is now available daily. We value employee health and will continue to add healthy choices to our menu based on your feedback.', 'Read the passage aloud with clear pronunciation and natural pacing.', 16),
(1, 'read_aloud', 'Remote Work Policy', E'Following the successful pilot program, the company has officially adopted a flexible remote work policy. Employees may work from home up to two days per week with manager approval. Core hours from 10 AM to 3 PM must be respected regardless of location. All remote workers must have a stable internet connection and a suitable workspace. Equipment requests for home offices can be submitted through the HR portal. Performance will be evaluated based on outcomes rather than hours logged.', 'Read the passage aloud with clear pronunciation and natural pacing.', 17),
(1, 'read_aloud', 'Conference Travel Update', E'The international sales conference will be held in Singapore from October 5th to 8th. Due to updated travel restrictions, all attendees must submit their vaccination certificates and travel insurance documents by September 20th. Hotel reservations have been made at the conference venue with a discounted rate of $180 per night. Please coordinate with your manager regarding budget approval for flights and daily allowances of $75. Receipts are required for all expenses.', 'Read the passage aloud with clear pronunciation and natural pacing.', 18),
(1, 'read_aloud', 'Employee Benefits Overview', E'Our updated employee benefits package includes expanded health insurance coverage, a new dental and vision plan, and an increased 401k matching contribution from 4% to 6%. Additional perks include gym membership discounts, tuition reimbursement up to $5,000 per year, and an increased paid time off allowance. Open enrollment for benefits begins on January 1st and ends on January 31st. Contact the HR benefits coordinator if you need assistance choosing the right plan for your situation.', 'Read the passage aloud with clear pronunciation and natural pacing.', 19),
(1, 'read_aloud', 'Website Maintenance Notice', E'Our company website will be undergoing scheduled maintenance this Saturday from 2 AM to 6 AM EST. During this time, the site may be intermittently unavailable. All online services including customer portals and order tracking will be temporarily offline. Our development team will be upgrading the server infrastructure to improve site speed and reliability. We apologize for any inconvenience and appreciate your patience during this necessary upgrade.', 'Read the passage aloud with clear pronunciation and natural pacing.', 20);

-- Part 2: Describe a Picture
INSERT INTO speaking_prompts (part_number, task_type, title, prompt, order_index) VALUES
(2, 'describe_picture', 'Business Meeting', 'Look at the picture and describe what you see in detail. Include information about the setting, people, activities, and any objects that are important.', 1),
(2, 'describe_picture', 'Office Workspace', 'Look at the picture and describe what you see in detail. Mention the objects, layout, and any notable features of the workspace.', 2),
(2, 'describe_picture', 'Airport Terminal', 'Look at the picture and describe what you see in detail. Include the setting, people activities, and any signs or information displayed.', 3),
(2, 'describe_picture', 'Restaurant Interior', 'Look at the picture and describe what you see in detail. Describe the atmosphere, furniture, decorations, and people present.', 4),
(2, 'describe_picture', 'Construction Site', 'Look at the picture and describe what you see in detail. Include safety equipment, machinery, workers, and the overall environment.', 5),
(2, 'describe_picture', 'Hospital Corridor', 'Look at the picture and describe what you see in detail. Include the medical equipment, signage, staff, and patient areas visible.', 6),
(2, 'describe_picture', 'Library Reading Room', 'Look at the picture and describe what you see in detail. Describe the shelves, seating areas, study materials, and atmosphere.', 7),
(2, 'describe_picture', 'Supermarket Aisles', 'Look at the picture and describe what you see in detail. Include the products, shelving, shopping carts, and customer activities.', 8),
(2, 'describe_picture', 'Train Station Platform', 'Look at the picture and describe what you see in detail. Include the trains, passengers, signage, and the overall environment.', 9),
(2, 'describe_picture', 'Hotel Lobby', 'Look at the picture and describe what you see in detail. Describe the furniture, decorations, reception area, and guests.', 10),
(2, 'describe_picture', 'Gym Workout Area', 'Look at the picture and describe what you see in detail. Include the equipment, people exercising, and the facility layout.', 11),
(2, 'describe_picture', 'School Classroom', 'Look at the picture and describe what you see in detail. Describe the desks, board, teacher, students, and learning materials.', 12),
(2, 'describe_picture', 'Beach Resort', 'Look at the picture and describe what you see in detail. Include the ocean, beach chairs, palm trees, and resort facilities.', 13),
(2, 'describe_picture', 'City Street View', 'Look at the picture and describe what you see in detail. Include the buildings, vehicles, pedestrians, and street signs.', 14),
(2, 'describe_picture', 'Conference Presentation', 'Look at the picture and describe what you see in detail. Describe the presenter, audience, screen, and room setup.', 15),
(2, 'describe_picture', 'Farm Landscape', 'Look at the picture and describe what you see in detail. Include the fields, barns, animals, and farming equipment.', 16),
(2, 'describe_picture', 'Shopping Mall', 'Look at the picture and describe what you see in detail. Include the storefronts, shoppers, decorations, and layout.', 17),
(2, 'describe_picture', 'Hospitality Kitchen', 'Look at the picture and describe what you see in detail. Describe the appliances, cookware, ingredients, and chef activities.', 18),
(2, 'describe_picture', 'Parking Garage', 'Look at the picture and describe what you see in detail. Include the vehicles, levels, signage, and lighting.', 19),
(2, 'describe_picture', 'Garden Park', 'Look at the picture and describe what you see in detail. Describe the plants, paths, benches, and people enjoying the space.', 20);

-- Part 3: Respond to Questions
INSERT INTO speaking_prompts (part_number, task_type, title, prompt, order_index) VALUES
(3, 'respond_questions', 'Work Preparation', 'What do you usually do to prepare for an important presentation at work or school?', 1),
(3, 'respond_questions', 'Learning Languages', 'What is the most challenging aspect of learning a new language? How do you overcome it?', 2),
(3, 'respond_questions', 'Daily Commute', 'Do you prefer public transportation or driving? Why? Describe your typical commute.', 3),
(3, 'respond_questions', 'Teamwork Experience', 'Describe a time when you had to work closely with difficult team members. How did you handle it?', 4),
(3, 'respond_questions', 'Healthy Habits', 'What habits do you follow to maintain your physical and mental health?', 5),
(3, 'respond_questions', 'Reading Preferences', 'Do you prefer reading books or watching movies? What are the advantages of your choice?', 6),
(3, 'respond_questions', 'Career Goals', 'Where do you see yourself professionally in five years? What steps are you taking to achieve this?', 7),
(3, 'respond_questions', 'Social Media', 'How has social media changed the way people communicate? What are the benefits and drawbacks?', 8),
(3, 'respond_questions', 'Shopping Habits', 'Do you prefer shopping in physical stores or online? Explain your preference with reasons.', 9),
(3, 'respond_questions', 'Childhood Memories', 'What is your most memorable experience from childhood? Why does it stay with you?', 10),
(3, 'respond_questions', 'Work Life Balance', 'How do you balance your professional responsibilities with your personal life?', 11),
(3, 'respond_questions', 'Technology Impact', 'What technology has had the biggest positive impact on your daily life? Why?', 12),
(3, 'respond_questions', 'Environmental Responsibility', 'What steps do you take in your daily life to protect the environment?', 13),
(3, 'respond_questions', 'Stress Management', 'How do you handle stressful situations? What strategies work best for you?', 14),
(3, 'respond_questions', 'Cultural Experiences', 'Describe a cultural experience that changed your perspective on something.', 15),
(3, 'respond_questions', 'Meal Planning', 'Do you usually cook at home or eat out? What influences your decision?', 16),
(3, 'respond_questions', 'Travel Destinations', 'What is your ideal vacation destination? Describe why you would choose that place.', 17),
(3, 'respond_questions', 'Time Management', 'How do you prioritize tasks when you have multiple deadlines? What methods do you use?', 18),
(3, 'respond_questions', 'Gift Giving', 'What factors do you consider when choosing a gift for someone important?', 19),
(3, 'respond_questions', 'Leadership Skills', 'What qualities make a good leader? Describe a leader you admire and explain why.', 20);

-- Part 4: Respond to Information
INSERT INTO speaking_prompts (part_number, task_type, title, prompt, order_index) VALUES
(4, 'respond_information', 'Train Schedule Inquiry', 'Based on the schedule shown, what is the earliest train the customer can take to arrive at the office by 8:30 AM?', 1),
(4, 'respond_information', 'Hotel Reservation', 'The customer wants to book a room for 3 nights starting Friday. Based on the information provided, what are the available room types and their prices?', 1),
(4, 'respond_information', 'Flight Options', 'A customer needs to travel from Hanoi to Ho Chi Minh City tomorrow afternoon. Based on the schedule, what flights are available and what is the difference in price between economy and business class?', 1),
(4, 'respond_information', 'Restaurant Menu', 'A customer is vegetarian and allergic to nuts. Based on the menu shown, which dishes would you recommend and what modifications are needed?', 1),
(4, 'respond_information', 'Car Rental Options', 'A customer needs a car for 5 days starting Monday. Based on the price list, what are the available car categories and their daily rates including insurance?', 1),
(4, 'respond_information', 'Medical Appointment', 'A patient needs to schedule a check-up with a general physician this week. Based on the doctor schedule, when are the next available slots?', 1),
(4, 'respond_information', 'Library Book Search', 'A customer is looking for books on time management published after 2020. Based on the catalog shown, which titles match the criteria?', 1),
(4, 'respond_information', 'Gym Membership', 'A prospective member wants to join the gym for 6 months with access to both the pool and fitness classes. Based on the membership options, what is the total cost and what are the benefits?', 1),
(4, 'respond_information', 'Job Application Status', 'An applicant is checking the status of their job application submitted two weeks ago. Based on the hiring timeline shown, what stage of the process are they currently in and when can they expect an update?', 1),
(4, 'respond_information', 'Utility Bill Inquiry', 'A customer noticed an unusually high electricity bill this month. Based on the usage breakdown shown, what were the peak usage periods and what suggestions would reduce the bill?', 1),
(4, 'respond_information', 'Insurance Claim', 'A policyholder wants to file a claim for a laptop that was damaged. Based on the policy document shown, what is the deductible amount and what is the maximum reimbursement limit?', 1),
(4, 'respond_information', 'Conference Registration', 'A professional wants to attend a 3-day conference and needs to know the registration deadlines, early bird discount cutoff, and what is included in the standard registration fee.', 1),
(4, 'respond_information', 'Tuition Fee Breakdown', 'A student is reviewing their tuition statement for the upcoming semester. Based on the fee schedule shown, what is the total cost including tuition, lab fees, and student services, and when is the payment due date?', 1),
(4, 'respond_information', 'Shipping Options', 'A customer wants to send a package weighing 5 kilograms to Australia within 7 days. Based on the shipping options shown, what are the available services, delivery times, and costs?', 1),
(4, 'respond_information', 'Phone Plan Comparison', 'A customer is looking for a plan with at least 20 GB of data and unlimited calls. Based on the plan options shown, which plans meet the requirements and what is the monthly cost difference?', 1),
(4, 'respond_information', 'Real Estate Viewing', 'A client wants to view apartments with 2 bedrooms in the downtown area with a budget of $2,000 per month. Based on the listings shown, which properties match the criteria?', 1),
(4, 'respond_information', 'Weather Advisory', 'Based on the weather forecast shown for the next 3 days, what activities would you recommend for each day and what precautions should be taken?', 1),
(4, 'respond_information', 'Bank Account Transfer', 'A customer wants to transfer $500 from their savings account to their checking account. Based on the account information shown, what are the current balances and will the transfer result in any fees?', 1),
(4, 'respond_information', 'Event Ticket Options', 'A group of 4 friends wants to attend a concert. Based on the seating chart and pricing shown, what are the available sections and what is the total cost for 4 tickets in the best available section?', 1),
(4, 'respond_information', 'Appliance Warranty', 'A customer is checking the warranty status of a refrigerator purchased 18 months ago. Based on the warranty terms shown, is the appliance still covered and what is the process for filing a service request?', 1);

-- Part 5: Express an Opinion
INSERT INTO speaking_prompts (part_number, task_type, title, prompt, order_index) VALUES
(5, 'express_opinion', 'Remote Work', 'Do you agree or disagree that working remotely increases productivity? Give at least two reasons and provide examples to support your opinion.', 1),
(5, 'express_opinion', 'Technology in Education', 'Do you think smartphones should be allowed in classrooms? Give at least two reasons and provide examples to support your opinion.', 2),
(5, 'express_opinion', 'Environmental Protection', 'Should governments impose higher taxes on companies that produce plastic packaging? Give at least two reasons and provide examples to support your opinion.', 3),
(5, 'express_opinion', 'Aging Population', 'Do you think the retirement age should be increased to address aging population challenges? Give at least two reasons and provide examples to support your opinion.', 4),
(5, 'express_opinion', 'Social Media Ban for Minors', 'Should social media platforms be banned for users under the age of 16? Give at least two reasons and provide examples to support your opinion.', 5),
(5, 'express_opinion', 'Universal Basic Income', 'Do you think governments should implement universal basic income for all citizens? Give at least two reasons and provide examples to support your opinion.', 6),
(5, 'express_opinion', 'Fast Food Advertising', 'Should fast food advertising be restricted or banned, especially during children''s programming? Give at least two reasons and provide examples to support your opinion.', 7),
(5, 'express_opinion', 'Online Privacy', 'Do you believe that individuals should have complete control over how their personal data is collected and used by companies? Give at least two reasons and provide examples to support your opinion.', 8),
(5, 'express_opinion', 'Space Exploration', 'Is it worthwhile for governments to spend billions of dollars on space exploration when there are pressing issues on Earth? Give at least two reasons and provide examples to support your opinion.', 9),
(5, 'express_opinion', 'Animal Testing', 'Should animal testing for cosmetic products be completely banned? Give at least two reasons and provide examples to support your opinion.', 10),
(5, 'express_opinion', 'Four-Day Work Week', 'Do you think companies should adopt a four-day work week? Give at least two reasons and provide examples to support your opinion.', 11),
(5, 'express_opinion', 'Mandatory Volunteering', 'Should community service be a mandatory requirement for high school graduation? Give at least two reasons and provide examples to support your opinion.', 12),
(5, 'express_opinion', 'Video Games', 'Do you think video games can be educational and beneficial for children? Give at least two reasons and provide examples to support your opinion.', 13),
(5, 'express_opinion', 'Plastic Surgery', 'Do you think cosmetic surgery should be regulated more strictly? Give at least two reasons and provide examples to support your opinion.', 14),
(5, 'express_opinion', 'Artificial Intelligence', 'Will artificial intelligence replace more jobs than it creates in the next decade? Give at least two reasons and provide examples to support your opinion.', 15),
(5, 'express_opinion', 'Standardized Testing', 'Should standardized tests like the TOEIC or TOEFL be the only measure of English proficiency for university admission? Give at least two reasons and provide examples to support your opinion.', 16),
(5, 'express_opinion', 'Urbanization', 'Is urbanization the best solution for managing growing populations? Give at least two reasons and provide examples to support your opinion.', 17),
(5, 'express_opinion', 'Homework', 'Should homework be abolished in primary schools? Give at least two reasons and provide examples to support your opinion.', 18),
(5, 'express_opinion', 'Genetic Engineering', 'Do you support the use of genetic engineering to enhance human capabilities? Give at least two reasons and provide examples to support your opinion.', 19),
(5, 'express_opinion', 'Tourism Impact', 'Do the economic benefits of tourism outweigh its negative effects on local cultures and environments? Give at least two reasons and provide examples to support your opinion.', 20);

-- ============================================================
-- Seed: writing_prompts (60 prompts: 20 per part)
-- ============================================================

-- Part 1: Write a Sentence Based on a Picture
INSERT INTO writing_prompts (part_number, title, prompt, image_url, passage_text, passage_subject, model_answer, hint_words, order_index) VALUES
(1, 'Office Scene', 'Write a sentence that describes what you see in the picture.', '', '', '', 'The employees are attending a meeting in the conference room.', ARRAY['employees', 'meeting', 'conference room'], 1),
(1, 'Cafe Scene', 'Write a sentence that describes what you see in the picture.', '', '', '', 'A customer is placing an order at the coffee shop counter.', ARRAY['customer', 'coffee shop', 'order'], 2),
(1, 'Airport Scene', 'Write a sentence that describes what you see in the picture.', '', '', '', 'The traveler is checking in for her flight at the airport counter.', ARRAY['traveler', 'check-in', 'airport'], 3),
(1, 'Construction Site', 'Write a sentence that describes what you see in the picture.', '', '', '', 'Workers are building a new office building on the construction site.', ARRAY['workers', 'building', 'construction site'], 4),
(1, 'Library Scene', 'Write a sentence that describes what you see in the picture.', '', '', '', 'Students are studying at the desks in the university library.', ARRAY['students', 'studying', 'library'], 5),
(1, 'Restaurant Scene', 'Write a sentence that describes what you see in the picture.', '', '', '', 'The waiter is serving food to customers at the restaurant table.', ARRAY['waiter', 'serving', 'restaurant'], 6),
(1, 'Factory Scene', 'Write a sentence that describes what you see in the picture.', '', '', '', 'Machines are operating in the factory assembly line.', ARRAY['machines', 'factory', 'assembly line'], 7),
(1, 'Hospital Scene', 'Write a sentence that describes what you see in the picture.', '', '', '', 'A doctor is examining a patient in the hospital examination room.', ARRAY['doctor', 'patient', 'hospital'], 8),
(1, 'Bank Scene', 'Write a sentence that describes what you see in the picture.', '', '', '', 'A customer is withdrawing money from the ATM machine.', ARRAY['customer', 'ATM', 'bank'], 9),
(1, 'Supermarket Scene', 'Write a sentence that describes what you see in the picture.', '', '', '', 'Shoppers are placing products into their shopping carts in the supermarket aisle.', ARRAY['shoppers', 'products', 'supermarket'], 10),
(1, 'Hotel Lobby', 'Write a sentence that describes what you see in the picture.', '', '', '', 'A guest is checking in at the hotel reception desk.', ARRAY['guest', 'check-in', 'hotel'], 11),
(1, 'School Scene', 'Write a sentence that describes what you see in the picture.', '', '', '', 'The teacher is explaining a lesson to students in the classroom.', ARRAY['teacher', 'lesson', 'classroom'], 12),
(1, 'Gym Scene', 'Write a sentence that describes what you see in the picture.', '', '', '', 'Members are exercising at the fitness equipment in the gym.', ARRAY['members', 'exercising', 'gym'], 13),
(1, 'Park Scene', 'Write a sentence that describes what you see in the picture.', '', '', '', 'Families are having picnics in the sunny public park.', ARRAY['families', 'picnic', 'park'], 14),
(1, 'Store Scene', 'Write a sentence that describes what you see in the picture.', '', '', '', 'A shop assistant is helping a customer choose clothes in the store.', ARRAY['assistant', 'customer', 'clothes'], 15),
(1, 'Train Station', 'Write a sentence that describes what you see in the picture.', '', '', '', 'Passengers are boarding the train at the station platform.', ARRAY['passengers', 'boarding', 'train'], 16),
(1, 'Delivery Scene', 'Write a sentence that describes what you see in the picture.', '', '', '', 'A delivery person is carrying a package to the customers door.', ARRAY['delivery', 'package', 'door'], 17),
(1, 'Garden Scene', 'Write a sentence that describes what you see in the picture.', '', '', '', 'Gardeners are planting flowers in the community garden.', ARRAY['gardeners', 'planting', 'flowers'], 18),
(1, 'Parking Lot', 'Write a sentence that describes what you see in the picture.', '', '', '', 'A driver is parking a car in the underground parking garage.', ARRAY['driver', 'parking', 'garage'], 19),
(1, 'Salon Scene', 'Write a sentence that describes what you see in the picture.', '', '', '', 'A hairdresser is cutting a customers hair in the beauty salon.', ARRAY['hairdresser', 'cutting', 'hair'], 20);

-- Part 2: Reply to an Email
INSERT INTO writing_prompts (part_number, title, prompt, passage_text, model_answer, hint_words, order_index) VALUES
(2, 'Respond to Project Invitation', 'The marketing team has sent you an email inviting you to join a new product launch project. Write a reply email accepting or declining the invitation and explaining your reason.', E'Subject: Invitation to Join Product Launch Project\n\nDear colleague,\n\nI am pleased to inform you that the marketing team is organizing a new product launch for our upcoming EcoClean line in April. We believe your experience in product management would be a valuable addition to our team.\n\nThe project will begin next Monday and will require approximately 5 hours per week of your time. If you are interested, please reply to this email by Friday.\n\nLooking forward to your response.\n\nBest regards,\nSarah Johnson\nMarketing Director', E'Subject: Re: Invitation to Join Product Launch Project\n\nDear Ms. Johnson,\n\nThank you for considering me for this opportunity. I am writing to express my interest and accept your invitation to join the EcoClean product launch team.\n\nI believe this project aligns well with my background in product management, and I am excited to contribute to the launch. I will ensure that my current responsibilities do not interfere with the 5 hours per week commitment.\n\nPlease let me know if you need any additional information from me before next Monday.\n\nBest regards,\n[Your Name]', ARRAY['accept', 'interest', 'product launch', 'schedule'], 1),
(2, 'Respond to Training Request', 'Your manager has sent you an email about attending a mandatory workplace safety training session. Write a reply email confirming your attendance or requesting a reschedule with a reason.', E'Subject: Mandatory Workplace Safety Training\n\nDear employee,\n\nAs part of our quarterly compliance requirements, all staff members are required to attend a workplace safety training session. The training will cover fire safety, emergency evacuation procedures, and first aid basics.\n\nSessions will be held in Conference Room A on March 20th at 2:00 PM and March 22nd at 10:00 AM. Please reply by March 15th to confirm your preferred session or request an alternative date if necessary.\n\nBest regards,\nHR Department', E'Subject: Re: Mandatory Workplace Safety Training\n\nDear HR Department,\n\nThank you for the notification regarding the workplace safety training. I would like to confirm my attendance at the session on March 20th at 2:00 PM.\n\nI understand the importance of this training and will ensure I am available to attend.\n\nBest regards,\n[Your Name]', ARRAY['confirm', 'attendance', 'safety training', 'available'], 2),
(2, 'Respond to Customer Complaint', 'A customer has emailed your company to complain about a defective product they received. Write a reply email apologizing and explaining the resolution steps.', E'Subject: Complaint About Defective Product\n\nDear Customer Service,\n\nI recently purchased a laptop from your online store and received it on March 5th. Unfortunately, the screen has a visible crack and the keyboard does not work properly.\n\nI would like to request a full refund or a replacement unit as soon as possible. I have attached photos of the damaged product for your reference.\n\nPlease respond at your earliest convenience.\n\nRegards,\nMr. Lee', E'Subject: Re: Complaint About Defective Product\n\nDear Mr. Lee,\n\nWe sincerely apologize for the inconvenience you have experienced with the laptop. We take product quality very seriously and understand your frustration.\n\nWe will arrange for a replacement unit to be shipped to you within 2 business days at no additional cost. A prepaid return label will be sent to you via email for returning the defective product.\n\nWe value your business and hope this resolution meets your expectations.\n\nBest regards,\nCustomer Service Team', ARRAY['apologize', 'replacement', 'refund', 'inconvenience'], 3),
(2, 'Respond to Schedule Change', 'Your colleague has emailed you about a change in the project deadline. Write a reply email acknowledging the change and confirming your adjusted work plan.', E'Subject: Updated Project Deadline\n\nHi,\n\nI wanted to inform you that the client has requested an earlier deadline for the quarterly report. The new deadline has been moved from April 15th to March 30th.\n\nCould you please update your task timeline and confirm if you can meet the new deadline? Let me know if you need any additional resources.\n\nThanks,\nTom', E'Subject: Re: Updated Project Deadline\n\nHi Tom,\n\nThank you for letting me know about the deadline change. I acknowledge the new deadline of March 30th for the quarterly report.\n\nI will adjust my work schedule accordingly and prioritize the remaining sections to ensure timely delivery. If any unexpected issues arise, I will inform you immediately.\n\nBest,\n[Your Name]', ARRAY['acknowledge', 'deadline', 'adjusted', 'schedule'], 4),
(2, 'Respond to Meeting Request', 'Your supervisor has emailed you requesting a one-on-one meeting to discuss your performance review. Write a reply email confirming the meeting time or suggesting an alternative.', E'Subject: One-on-One Meeting Request\n\nDear team member,\n\nI would like to schedule a one-on-one meeting with you to discuss your recent performance review and set goals for the upcoming quarter.\n\nI am available on April 5th at 3:00 PM or April 6th at 11:00 AM. Please let me know which time works best for you.\n\nBest regards,\n[Supervisor Name]', E'Subject: Re: One-on-One Meeting Request\n\nDear Supervisor,\n\nThank you for reaching out. I would be happy to meet and discuss my performance review.\n\nApril 5th at 3:00 PM works well for me. I look forward to our meeting and discussing my goals for the next quarter.\n\nBest regards,\n[Your Name]', ARRAY['confirm', 'meeting', 'available', 'performance'], 5),
(2, 'Respond to Conference Invitation', 'An organizer has emailed you about speaking at an industry conference. Write a reply email expressing your interest and asking for more details.', E'Subject: Speaking Opportunity at TOEIC Summit 2026\n\nDear expert,\n\nWe are organizing the TOEIC Summit 2026 conference and would be honored to have you speak on the topic of AI in language education.\n\nThe event will take place on May 15th in Ho Chi Minh City. If you are interested, please reply with your availability and any specific requirements for your session.\n\nBest regards,\nConference Committee', E'Subject: Re: Speaking Opportunity at TOEIC Summit 2026\n\nDear Conference Committee,\n\nThank you for reaching out and inviting me to speak at the TOEIC Summit 2026. I am very interested in this opportunity and would like to learn more details.\n\nCould you please provide information about the expected session length, target audience size, and whether travel and accommodation expenses are covered?\n\nI look forward to hearing from you.\n\nBest regards,\n[Your Name]', ARRAY['interested', 'opportunity', 'details', 'conference'], 6),
(2, 'Respond to Invoice Inquiry', 'A client has emailed your company asking about an overdue invoice. Write a reply email confirming the payment status and providing the next steps.', E'Subject: Inquiry About Invoice #INV-2024-089\n\nDear Accounts Department,\n\nWe received your invoice #INV-2024-089 for $2,500 dated February 28th. However, our records show that this amount was already paid on March 3rd via bank transfer.\n\nCould you please verify your records and confirm receipt of the payment? If not received, please find attached the bank transfer receipt.\n\nRegards,\nFinance Team', E'Subject: Re: Inquiry About Invoice #INV-2024-089\n\nDear Finance Team,\n\nThank you for bringing this to our attention. We have reviewed our records and confirmed that the payment of $2,500 for invoice #INV-2024-089 was received on March 3rd.\n\nOur accounts team has updated the payment status in our system. An official receipt will be sent to your email within 2 business days.\n\nWe apologize for any confusion and appreciate your patience.\n\nBest regards,\nAccounts Department', ARRAY['confirmed', 'payment', 'receipt', 'received'], 7),
(2, 'Respond to Supplier Delay', 'Your supplier has emailed you explaining a delay in your order delivery. Write a reply email acknowledging the delay and requesting an updated delivery date.', E'Subject: Delay in Order #ORD-5567\n\nDear valued client,\n\nWe regret to inform you that your order #ORD-5567, originally scheduled for delivery on March 10th, has been delayed due to unexpected shipping disruptions.\n\nThe new estimated delivery date is March 20th. We sincerely apologize for any inconvenience this may cause.\n\nBest regards,\nSupply Chain Team', E'Subject: Re: Delay in Order #ORD-5567\n\nDear Supply Chain Team,\n\nThank you for informing us about the delay in order #ORD-5567. We understand that shipping disruptions can happen unexpectedly.\n\nCould you please confirm the exact updated delivery date of March 20th and provide tracking information once the order is shipped?\n\nWe look forward to receiving the order as soon as possible.\n\nBest regards,\n[Your Name]', ARRAY['delay', 'delivery', 'understand', 'updated'], 8),
(2, 'Respond to Job Offer', 'A company has sent you a job offer email. Write a reply email accepting the offer and asking about the start date and onboarding process.', E'Subject: Job Offer for Marketing Manager Position\n\nDear candidate,\n\nWe are pleased to offer you the position of Marketing Manager at our company. After careful consideration of all candidates, we believe your skills and experience make you the ideal fit for this role.\n\nThe starting salary is $85,000 per year with benefits including health insurance and 20 days of paid leave. Please reply by April 10th to confirm your acceptance.\n\nBest regards,\nHR Recruitment Team', E'Subject: Re: Job Offer for Marketing Manager Position\n\nDear HR Recruitment Team,\n\nThank you very much for offering me the Marketing Manager position. I am delighted to accept the offer and look forward to joining the team.\n\nI would appreciate more information about the official start date and any documents or preparations required before my first day.\n\nThank you again for this opportunity.\n\nBest regards,\n[Your Name]', ARRAY['accept', 'offer', 'position', 'start date'], 9),
(2, 'Respond to IT Support Request', 'The IT department has emailed you about resolving a software issue on your computer. Write a reply email confirming the issue is resolved and thanking them for their help.', E'Subject: Resolved: Software Installation Issue\n\nDear user,\n\nOur IT technician has completed the installation of the required software on your computer. The issue with the network connection has also been addressed by updating the network drivers.\n\nPlease restart your computer and verify that everything is working correctly. If you experience any further issues, do not hesitate to contact us.\n\nBest regards,\nIT Support Team', E'Subject: Re: Resolved: Software Installation Issue\n\nDear IT Support Team,\n\nThank you for promptly resolving the software installation issue on my computer. I have restarted my computer as instructed and can confirm that everything is now working correctly.\n\nI appreciate your efficient and professional support.\n\nBest regards,\n[Your Name]', ARRAY['resolved', 'working', 'thanks', 'support'], 10),
(2, 'Respond to Reservation Confirmation', 'A hotel has emailed you confirming your reservation. Write a reply email confirming the details and asking about early check-in options.', E'Subject: Hotel Reservation Confirmed - Booking #HTL-88432\n\nDear guest,\n\nYour reservation at Grand Plaza Hotel has been confirmed. Here are your booking details:\nCheck-in: April 12th, 2026\nCheck-out: April 15th, 2026\nRoom type: Deluxe Double\nNumber of guests: 2\n\nPlease present this confirmation email upon check-in. Early check-in is subject to availability.\n\nBest regards,\nReservations Team', E'Subject: Re: Hotel Reservation Confirmed - Booking #HTL-88432\n\nDear Reservations Team,\n\nThank you for confirming my reservation at Grand Plaza Hotel. I would like to verify the booking details:\nCheck-in: April 12th\nCheck-out: April 15th\nDeluxe Double room for 2 guests\n\nCould you also let me know if early check-in at 10:00 AM is possible, and if so, what the additional charge would be?\n\nThank you,\n[Your Name]', ARRAY['confirmed', 'reservation', 'details', 'early check-in'], 11),
(2, 'Respond to Partnership Proposal', 'A company has emailed you proposing a business partnership. Write a reply email expressing interest and requesting more information about the terms.', E'Subject: Business Partnership Proposal\n\nDear partner,\n\nOur company is exploring potential partnerships with innovative businesses in the education technology sector. Your platform aligns well with our strategic goals.\n\nWe would like to schedule a meeting to discuss potential collaboration opportunities. Please let us know your availability for a video call next week.\n\nBest regards,\nBusiness Development', E'Subject: Re: Business Partnership Proposal\n\nDear Business Development Team,\n\nThank you for reaching out regarding a potential business partnership. We are very interested in exploring this opportunity with you.\n\nBefore we schedule a call, could you please provide more details about the type of partnership you are proposing and the terms you have in mind?\n\nWe look forward to discussing how we can work together.\n\nBest regards,\n[Your Name]', ARRAY['interested', 'partnership', 'collaboration', 'details'], 12),
(2, 'Respond to Subscription Renewal', 'A service provider has emailed you about renewing your annual subscription. Write a reply email confirming the renewal and asking about any available upgrades.', E'Subject: Subscription Renewal Reminder - Expiring April 30th\n\nDear subscriber,\n\nYour annual subscription for CloudPro services will expire on April 30th, 2026. To ensure uninterrupted service, please confirm your renewal before the expiration date.\n\nWe are also offering a 20% discount if you upgrade to our Business Plan before renewal.\n\nBest regards,\nCustomer Success Team', E'Subject: Re: Subscription Renewal Reminder - Expiring April 30th\n\nDear Customer Success Team,\n\nThank you for the renewal reminder. I would like to confirm the renewal of my CloudPro subscription before April 30th.\n\nCould you provide more details about the Business Plan upgrade? I am interested in learning about the additional features and the discounted price.\n\nBest regards,\n[Your Name]', ARRAY['renewal', 'subscription', 'upgrade', 'confirm'], 13),
(2, 'Respond to Feedback Request', 'Your manager has emailed you asking for feedback on the new office layout. Write a reply email providing your honest opinion and suggestions.', E'Subject: Feedback on New Office Layout\n\nDear team,\n\nWe have recently redesigned the office layout to create more collaborative workspaces. We value your opinion and would like to hear your thoughts on the new arrangement.\n\nPlease share any feedback, positive or negative, along with any suggestions for improvement by March 25th.\n\nBest regards,\nOffice Management', E'Subject: Re: Feedback on New Office Layout\n\nDear Office Management,\n\nThank you for asking for our feedback on the new office layout. Here are my thoughts:\n\nOverall, I appreciate the effort to create more collaborative spaces. The open discussion areas are very useful for team meetings. However, I find the noise level in the open workspace distracting at times.\n\nMy suggestion would be to add a few private phone booths for calls and quiet work areas.\n\nThank you for considering our input.\n\nBest regards,\n[Your Name]', ARRAY['feedback', 'layout', 'collaborative', 'suggestion'], 14),
(2, 'Respond to Delivery Update', 'A shipping company has emailed you about an unsuccessful delivery attempt. Write a reply email rescheduling the delivery and providing your preferred time window.', E'Subject: Delivery Attempt Unsuccessful - Action Required\n\nDear recipient,\n\nOur delivery driver attempted to deliver your package on March 18th at 9:45 AM, but no one was available to receive it.\n\nPlease reschedule your delivery by March 22nd by visiting our website or contacting us directly. After this date, the package will be returned to the sender.\n\nBest regards,\nDelivery Team', E'Subject: Re: Delivery Attempt Unsuccessful - Action Required\n\nDear Delivery Team,\n\nThank you for the notification about the unsuccessful delivery attempt.\n\nI would like to reschedule the delivery for March 21st between 2:00 PM and 5:00 PM, as I will be working from home that afternoon.\n\nPlease confirm the updated delivery time.\n\nBest regards,\n[Your Name]', ARRAY['reschedule', 'delivery', 'available', 'confirm'], 15),
(2, 'Respond to Price Increase Notice', 'A vendor has emailed you informing about a price increase for their products. Write a reply email acknowledging the notice and negotiating if possible.', E'Subject: Price Adjustment Notice - Effective May 1st\n\nDear client,\n\nDue to rising production costs, we will be adjusting our prices by 10% effective May 1st, 2026. Current orders placed before May 1st will be honored at the existing prices.\n\nWe value your continued partnership and hope you understand the necessity of this adjustment.\n\nBest regards,\nSales Department', E'Subject: Re: Price Adjustment Notice - Effective May 1st\n\nDear Sales Department,\n\nThank you for informing us about the upcoming price adjustment effective May 1st.\n\nWe understand that production costs fluctuate and appreciate your transparency. However, a 10% increase will significantly impact our budget. Would it be possible to negotiate a smaller increase, perhaps 5%, especially given our long-standing relationship?\n\nWe look forward to your response.\n\nBest regards,\n[Your Name]', ARRAY['acknowledge', 'increase', 'negotiate', 'budget'], 16),
(2, 'Respond to Internship Application', 'A student has emailed your company asking about internship opportunities. Write a reply email as HR, providing information about the application process.', E'Subject: Inquiry About Internship Opportunities\n\nDear sir or madam,\n\nI am a third-year university student majoring in Computer Science. I am interested in applying for a summer internship at your company.\n\nCould you please provide information about available internship positions, the application deadline, and the required qualifications?\n\nThank you,\n[Student Name]', E'Subject: Re: Inquiry About Internship Opportunities\n\nDear student,\n\nThank you for your interest in our internship program. We welcome applications from motivated students like yourself.\n\nWe are currently accepting applications for summer internships in Software Development, Product Management, and Marketing. The application deadline is April 30th. Please submit your resume and a cover letter through our careers page at careers.company.com.\n\nWe encourage you to apply before the deadline.\n\nBest regards,\nHR Team', ARRAY['internship', 'application', 'deadline', 'resume'], 17),
(2, 'Respond to Warranty Claim', 'A customer has emailed your company claiming warranty service for a broken appliance. Write a reply email confirming the warranty coverage and next steps.', E'Subject: Warranty Service Request for Refrigerator\n\nDear Customer Support,\n\nI purchased a SmartCool refrigerator from your store in October 2024. The refrigerator has stopped cooling properly, and the digital display is not working. The product is still within the 2-year warranty period.\n\nPlease advise on how to proceed with a warranty claim.\n\nRegards,\nMrs. Nguyen', E'Subject: Re: Warranty Service Request for Refrigerator\n\nDear Mrs. Nguyen,\n\nThank you for contacting us about your SmartCool refrigerator. We are sorry to hear about the issues you are experiencing.\n\nSince your product is within the 2-year warranty period, you are eligible for free repair service. We will arrange for a certified technician to visit your home within 3 business days to diagnose and repair the refrigerator.\n\nPlease reply with your preferred appointment date, time, and home address.\n\nBest regards,\nWarranty Service Team', ARRAY['warranty', 'repair', 'technician', 'service'], 18),
(2, 'Respond to Team Lunch Invitation', 'A colleague has emailed you inviting you to a team lunch. Write a reply email accepting the invitation and suggesting a restaurant.', E'Subject: Team Lunch This Friday!\n\nHi everyone,\n\nLet us celebrate the successful project completion with a team lunch this Friday at 12:30 PM. Please reply by Wednesday if you can make it and share any restaurant preferences.\n\nBest,\nJohn', E'Subject: Re: Team Lunch This Friday!\n\nHi John,\n\nCount me in for the team lunch this Friday at 12:30 PM! That sounds like a great way to celebrate.\n\nI suggest we try the new Vietnamese restaurant on Nguyen Hue Street. They have excellent pho and a private room for groups.\n\nLooking forward to it!\n\nBest,\n[Your Name]', ARRAY['accept', 'lunch', 'celebrate', 'restaurant'], 19),
(2, 'Respond to System Outage', 'Your IT department has emailed you about a planned system maintenance. Write a reply email confirming the maintenance schedule and asking about emergency access.', E'Subject: Planned System Maintenance - March 28th\n\nDear users,\n\nOur IT team will perform critical system maintenance on March 28th from 10:00 PM to 2:00 AM. During this period, all company systems including email, project management tools, and the CRM will be unavailable.\n\nPlease save your work and log out before 9:30 PM on March 28th.\n\nBest regards,\nIT Operations', E'Subject: Re: Planned System Maintenance - March 28th\n\nDear IT Operations,\n\nThank you for the notice about the planned system maintenance on March 28th.\n\nI will ensure all my work is saved and the system is logged out before 9:30 PM. However, I may need emergency access to the CRM during the maintenance window for an urgent client matter. Is there a contact number or alternative method to reach IT support during that time?\n\nBest regards,\n[Your Name]', ARRAY['maintenance', 'systems', 'unavailable', 'emergency'], 20);

-- Part 3: Write an Opinion Essay
INSERT INTO writing_prompts (part_number, title, prompt, model_answer, hint_words, order_index) VALUES
(3, 'Remote Work Policy', 'Some companies are allowing employees to work from home permanently. Do you think this is a positive development? Give at least two reasons and support your opinion with examples.', E'I believe that allowing employees to work from home permanently is a positive development for several compelling reasons.\n\nFirst, working from home significantly improves work-life balance. Employees no longer need to spend hours commuting to and from the office, which saves an average of two hours per day. This time can be used for family, exercise, or personal development. For instance, many workers report that remote work has allowed them to pursue hobbies and spend more quality time with their families, resulting in reduced stress and higher job satisfaction.\n\nSecond, remote work can increase productivity. Without the distractions of an open office environment, such as background noise and impromptu interruptions, employees can focus better on their tasks. Studies have shown that remote workers often complete their work more efficiently and maintain higher quality standards. A survey by Stanford University found that remote workers are 13% more productive than their office-based counterparts.\n\nHowever, some argue that remote work may reduce team collaboration and company culture. While this is a valid concern, regular video meetings and virtual team-building activities can effectively address these issues. Many companies have successfully maintained strong team cohesion through digital platforms.\n\nIn conclusion, I strongly believe that permanent remote work is a positive trend. The benefits of improved work-life balance and increased productivity far outweigh the challenges, especially when companies invest in proper digital collaboration tools.', ARRAY['work from home', 'productivity', 'balance', 'communication', 'collaboration'], 1),
(3, 'Technology in Education', 'Some people believe that technology has more benefits than drawbacks in education. Do you agree or disagree? Give at least two reasons and support your opinion with examples.', E'I strongly agree that technology brings more benefits than drawbacks to education. Here are my reasons.\n\nFirst, technology provides students with access to a vast amount of information and resources. With the internet, students can research any topic, watch educational videos, and participate in online courses from top universities around the world. For example, platforms like Coursera and Khan Academy allow learners to access high-quality education regardless of their geographical location or financial situation.\n\nSecond, technology enhances the learning experience through interactive tools. Educational apps, virtual laboratories, and gamified lessons make learning more engaging and effective. Students who struggle with traditional textbook learning often excel when taught through interactive digital platforms. Additionally, adaptive learning software can personalize education by adjusting difficulty levels based on individual student performance.\n\nSome critics argue that technology may cause distractions and reduce face-to-face interaction. While this is a legitimate concern, proper digital citizenship education and well-designed learning management systems can mitigate these issues effectively.\n\nIn conclusion, technology has transformed education for the better. Its ability to democratize access to knowledge and create engaging learning experiences makes it an indispensable tool in modern education.', ARRAY['technology', 'education', 'access', 'interactive', 'learning'], 2),
(3, 'Advertising', 'Do you think companies should be allowed to advertise products to children? Give at least two reasons and support your opinion with examples.', E'I believe that companies should NOT be allowed to advertise products to children, and I will explain my reasons below.\n\nFirst, children lack the cognitive ability to critically evaluate advertising messages. They cannot distinguish between informative content and persuasive advertising, making them highly susceptible to manipulative marketing tactics. For instance, fast food companies that advertise sugary cereals and drinks to children contribute to rising childhood obesity rates and poor dietary habits.\n\nSecond, advertising to children often exploits the parent-child relationship. Children who are exposed to advertisements may pressure their parents to purchase products they cannot afford, creating financial strain and unhealthy consumption patterns. Toys and gadgets advertised on children television programs frequently lead to impulsive purchasing decisions by both children and parents.\n\nFurthermore, early exposure to commercial messages can shape lifelong consumption habits that prioritize material goods over essential needs and experiences.\n\nWhile some argue that advertising supports free market economics and funds children entertainment, the potential harm to children wellbeing and family finances outweighs these economic benefits.\n\nIn conclusion, banning advertising to children is necessary to protect their physical health, financial wellbeing of their families, and their development as responsible consumers.', ARRAY['advertising', 'children', 'exploit', 'manipulate', 'protect'], 3),
(3, 'Urbanization', 'Do you think urbanization has more advantages than disadvantages? Give at least two reasons and support your opinion with examples.', E'I believe that urbanization offers more advantages than disadvantages, particularly for developing economies.\n\nFirst, cities are engines of economic growth and opportunity. They concentrate businesses, talent, and infrastructure in ways that create employment and drive innovation. For example, major cities like Ho Chi Minh City and Hanoi attract both domestic and foreign investment, generating millions of jobs in sectors ranging from technology to services.\n\nSecond, urbanization improves access to essential services such as healthcare, education, and transportation. City residents typically have better access to hospitals, universities, and public transit systems compared to rural populations. This concentration of services leads to higher quality of life and greater social mobility for residents.\n\nThird, cities foster cultural exchange and diversity. People from different backgrounds come together in urban areas, creating vibrant communities that celebrate diversity and promote creativity. This cultural melting pot often leads to innovation in arts, cuisine, and social norms.\n\nCritics point to challenges such as traffic congestion, pollution, and housing shortages as evidence against urbanization. However, well-planned cities with effective governance can address these issues through sustainable development policies.\n\nIn conclusion, the economic opportunities, improved services, and cultural richness that cities provide make urbanization a net positive for society.', ARRAY['urbanization', 'economic', 'opportunity', 'services', 'growth'], 4),
(3, 'Standardized Testing', 'Some people believe that standardized tests are the best way to measure student achievement. Others think they are unfair and limited. What is your opinion? Give at least two reasons and support your opinion with examples.', E'I believe that standardized tests are useful but should not be the only measure of student achievement. Here are my reasons.\n\nFirst, standardized tests provide valuable objective comparisons across schools and regions. They offer a consistent benchmark that allows educators and parents to identify areas where students need improvement. For instance, national standardized tests can reveal disparities in educational quality between urban and rural schools, enabling policymakers to allocate resources more effectively.\n\nSecond, standardized tests promote accountability and effort. Knowing that their performance will be measured objectively encourages students to study consistently and take their education seriously. This structured approach helps ensure that all students master essential knowledge and skills.\n\nHowever, standardized tests have significant limitations. They primarily measure recall and test-taking skills rather than creativity, critical thinking, or practical application of knowledge. A student who excels in art or music may perform poorly on standardized tests despite having exceptional abilities.\n\nFurthermore, excessive reliance on standardized testing can lead to teaching to the test, narrowing the curriculum, and increasing student stress. The pressure to achieve high scores can negatively impact students mental health and love of learning.\n\nIn conclusion, standardized tests should complement rather than replace other assessment methods such as portfolios, projects, and teacher evaluations to provide a comprehensive picture of student achievement.', ARRAY['standardized tests', 'measure', 'achievement', 'objective', 'limitations'], 5),
(3, 'Social Media', 'Do you think social media has a positive or negative effect on society? Give at least two reasons and support your opinion with examples.', E'I believe that social media has both positive and negative effects, but overall its negative impacts outweigh its benefits.\n\nFirst, social media contributes to the spread of misinformation and fake news. False information can go viral within hours, leading to confusion, panic, and harmful decision-making. During the COVID-19 pandemic, social media was flooded with misinformation about treatments and vaccines, endangering public health efforts.\n\nSecond, social media platforms are associated with mental health problems, particularly among young people. Studies have shown that excessive use of social media is linked to anxiety, depression, and low self-esteem. The constant comparison to idealized lives portrayed online can make users, especially teenagers, feel inadequate and dissatisfied with their own lives.\n\nThird, social media reduces the quality of real social interactions. People spend more time communicating through screens and less time engaging in face-to-face conversations, which are essential for building deep and meaningful relationships.\n\nWhile social media does offer benefits such as connecting people across distances and providing platforms for activism, the serious harms to mental health and social cohesion are too significant to ignore.\n\nIn conclusion, society must find ways to regulate social media more effectively to minimize its negative effects while preserving its genuine benefits.', ARRAY['social media', 'misinformation', 'mental health', 'society', 'negative'], 6),
(3, 'Environmental Protection', 'Should governments impose higher taxes on companies that cause pollution? Give at least two reasons and support your opinion with examples.', E'I strongly believe that governments should impose higher taxes on polluting companies. Here are my reasons.\n\nFirst, pollution taxes create financial incentives for companies to adopt cleaner technologies and sustainable practices. When companies must pay higher taxes for their environmental damage, they are motivated to invest in pollution reduction measures. For example, several European countries have successfully used carbon taxes to reduce industrial emissions significantly.\n\nSecond, pollution taxes generate revenue that can be used to fund environmental restoration and public health initiatives. The money collected can be invested in reforestation projects, cleaning contaminated waterways, and improving air quality in urban areas. These investments benefit both the environment and public health.\n\nThird, pollution taxes promote fairness by ensuring that companies bear the true cost of their production. Currently, taxpayers often subsidize the cleanup of environmental damage caused by polluting industries. A pollution tax corrects this market failure by internalizing environmental costs.\n\nCritics argue that pollution taxes may harm businesses and reduce competitiveness. However, when implemented with appropriate exemptions for small businesses and transition periods, these taxes can drive innovation in clean technology while maintaining economic growth.\n\nIn conclusion, higher pollution taxes are an effective and fair policy tool that incentivizes environmental responsibility, funds remediation efforts, and ensures polluters pay their true share of costs.', ARRAY['pollution', 'taxes', 'environment', 'government', 'incentives'], 7),
(3, 'Video Games', 'Do you think video games can be beneficial for children and teenagers? Give at least two reasons and support your opinion with examples.', E'I believe that video games can be beneficial for children and teenagers when played in moderation.\n\nFirst, many video games develop cognitive skills such as problem-solving, strategic thinking, and spatial awareness. Puzzle games and strategy games require players to analyze situations, make decisions quickly, and adapt to changing conditions. For example, games like Minecraft encourage creativity and resource management, while action games can improve reaction time and hand-eye coordination.\n\nSecond, multiplayer video games provide opportunities for social interaction and teamwork. Children and teenagers who play online games with friends learn to collaborate, communicate effectively, and coordinate strategies to achieve common goals. These social skills are valuable in both online and offline environments.\n\nThird, educational video games can reinforce academic learning. Games that teach mathematics, science, history, and language skills engage students in ways that traditional textbooks cannot. When learning is gamified, students often retain information better and develop more positive attitudes toward education.\n\nHowever, excessive gaming can lead to addiction, physical health problems, and academic decline. Parents should set reasonable time limits and ensure that gaming does not replace important activities such as physical exercise, homework, and family time.\n\nIn conclusion, video games offer genuine educational and developmental benefits, but they should be enjoyed in balance with other healthy activities.', ARRAY['video games', 'benefits', 'cognitive', 'social', 'education'], 8),
(3, 'Aging Population', 'Do you think the retirement age should be increased to address aging population challenges? Give at least two reasons and support your opinion with examples.', E'I believe that increasing the retirement age is a reasonable measure to address aging population challenges, but it should be implemented carefully.\n\nFirst, people are living longer and healthier lives than previous generations. With advances in healthcare, many individuals in their sixties are still physically and mentally capable of productive work. Keeping these experienced workers in the labor force helps address labor shortages and maintains economic productivity. Countries like Japan and Germany, which have faced severe aging populations, have successfully raised their retirement ages to retain experienced workers.\n\nSecond, increasing the retirement age helps sustain pension and social security systems. When people live longer, pension funds face greater financial pressure. Raising the retirement age reduces the number of years that pensions must be paid, helping to ensure the long-term viability of retirement benefits for all citizens.\n\nHowever, this policy may disproportionately affect workers in physically demanding jobs who may not be able to work into their late sixties or seventies. Governments should provide support for retraining and offer flexible retirement options.\n\nIn conclusion, a gradual and carefully designed increase in the retirement age, accompanied by support for workers in physically demanding occupations, is an appropriate response to the challenges of an aging population.', ARRAY['retirement', 'aging', 'population', 'pension', 'productivity'], 9),
(3, 'Four-Day Work Week', 'Do you think companies should adopt a four-day work week? Give at least two reasons and support your opinion with examples.', E'I believe that companies should seriously consider adopting a four-day work week, as it offers significant benefits for both employers and employees.\n\nFirst, numerous studies have shown that a four-day work week increases productivity. When employees have more time to rest and recharge, they return to work more focused and energized. A recent pilot program in Iceland reported that workers were equally or more productive while working fewer hours, and they reported significantly higher job satisfaction.\n\nSecond, a shorter work week improves employee wellbeing and reduces burnout. Modern workers often struggle with work-life balance, leading to stress, anxiety, and health problems. An extra day off allows employees to spend time with family, pursue personal interests, and take care of essential tasks, resulting in better mental and physical health.\n\nThird, a four-day work week can benefit the environment by reducing energy consumption and commuting. If offices are closed one day per week, less electricity and heating are used, and millions of commuting trips are eliminated, contributing to lower carbon emissions.\n\nWhile some critics worry that a four-day week may reduce customer service availability, many companies have successfully implemented it by staggering schedules and maintaining adequate coverage.\n\nIn conclusion, the four-day work week represents a promising approach that benefits employees, employers, and the environment simultaneously.', ARRAY['four-day work week', 'productivity', 'wellbeing', 'balance', 'benefits'], 10),
(3, 'Homework', 'Do you think homework should be abolished in primary schools? Give at least two reasons and support your opinion with examples.', E'I do not think homework should be completely abolished in primary schools, but it should be significantly reduced and redesigned.\n\nFirst, appropriate homework reinforces learning and helps students practice skills taught in class. Research has consistently shown that short, targeted homework assignments improve retention of knowledge and develop good study habits. For example, reading practice at home strengthens literacy skills that are foundational to all future learning.\n\nSecond, homework provides parents with insight into their children academic progress. When parents help with or review their children homework, they become more aware of what is being taught in school and can identify areas where their child may need additional support.\n\nHowever, excessive homework can have negative effects. Too much homework causes stress, reduces time for play and physical activities, and can create conflict within families. Studies have shown that primary students who spend more than one hour on homework daily may actually perform worse academically due to fatigue and loss of interest.\n\nThe key is balance. Homework for primary school students should be limited to 30-60 minutes per week and should consist of engaging, age-appropriate activities such as reading, basic math practice, or creative projects.\n\nIn conclusion, homework should be reformed rather than abolished to maximize its educational benefits while minimizing its harmful effects on children wellbeing.', ARRAY['homework', 'primary school', 'learning', 'practice', 'balance'], 11),
(3, 'Online Privacy', 'Do you believe individuals should have complete control over how their personal data is collected and used by companies? Give at least two reasons and support your opinion with examples.', E'I strongly believe that individuals should have complete control over how their personal data is collected and used by companies.\n\nFirst, personal data is a fundamental aspect of individual privacy and dignity. Companies that collect data about browsing habits, location, purchases, and social interactions are building detailed profiles of individuals without fully transparent consent. This information can be used in ways that discriminate against certain groups or manipulate consumer behavior, undermining personal autonomy.\n\nSecond, the misuse of personal data can lead to serious consequences including identity theft, financial fraud, and reputational damage. High-profile data breaches at major companies have exposed millions of peoples private information, leading to significant financial and emotional harm.\n\nThird, the power imbalance between large technology corporations and individual users means that without strong data protection rights, people are essentially powerless against invasive data collection practices. Regulations such as GDPR in Europe have begun to address this imbalance by giving individuals the right to access, correct, and delete their data.\n\nSome argue that data collection is necessary for companies to provide personalized services. However, personalization can be achieved without invasive tracking if companies adopt privacy-preserving technologies and practices.\n\nIn conclusion, robust data protection laws that give individuals full control over their personal information are essential in the digital age.', ARRAY['online privacy', 'personal data', 'control', 'protection', 'consent'], 12),
(3, 'Space Exploration', 'Is it worthwhile for governments to spend billions of dollars on space exploration when there are pressing issues on Earth? Give at least two reasons and support your opinion with examples.', E'I believe that space exploration is worthwhile and should continue despite the existence of pressing issues on Earth.\n\nFirst, space programs drive significant technological innovation that benefits life on Earth. Technologies developed for space missions have led to breakthroughs in medicine, materials science, computing, and renewable energy. For example, NASA research has contributed to water purification systems, memory foam, and satellite-based weather forecasting that saves countless lives each year.\n\nSecond, space exploration addresses long-term human survival. As resources on Earth become scarcer and environmental challenges intensify, developing the capability to inhabit other planets or harvest space resources may become essential for human survival. Investing in space technology today is an investment in humanitys future.\n\nThird, the economic returns from space programs often exceed the investment. The space industry generates billions of dollars in revenue and creates high-skilled jobs. Additionally, satellite technology, which relies on space infrastructure, is critical for global communications, navigation, and climate monitoring.\n\nWhile addressing poverty, disease, and climate change on Earth is urgent, these investments are not mutually exclusive. Space budgets typically represent a tiny fraction of government spending compared to social programs.\n\nIn conclusion, space exploration is a worthwhile investment that generates technological spinoffs, ensures long-term human survival, and stimulates economic growth.', ARRAY['space exploration', 'technology', 'innovation', 'investment', 'future'], 13),
(3, 'Mandatory Volunteering', 'Should community service be a mandatory requirement for high school graduation? Give at least two reasons and support your opinion with examples.', E'I believe that mandatory community service should be a graduation requirement for high school students, as it offers valuable developmental benefits.\n\nFirst, community service exposes students to diverse communities and social issues, fostering empathy and civic responsibility. When students volunteer at shelters, hospitals, or environmental projects, they gain firsthand understanding of challenges faced by different groups in society. This experience helps them become more compassionate and engaged citizens.\n\nSecond, volunteering develops practical skills that are not taught in traditional classrooms. Students learn teamwork, communication, time management, and problem-solving through real-world service experiences. These skills are highly valued by universities and employers alike.\n\nThird, community service can help students discover career interests and build professional networks. A student who volunteers at a veterinary clinic may realize a passion for animal medicine, while another who tutors younger children may decide to pursue education as a career.\n\nSome argue that mandating volunteering contradicts the spirit of service by forcing altruism. However, school requirements can be designed to include a wide variety of service options, allowing students to choose causes they genuinely care about.\n\nIn conclusion, mandatory community service for high school graduation is a valuable policy that develops empathy, practical skills, and civic engagement in young people.', ARRAY['community service', 'volunteering', 'graduation', 'civic', 'skills'], 14),
(3, 'Tourism Impact', 'Do the economic benefits of tourism outweigh its negative effects on local cultures and environments? Give at least two reasons and support your opinion with examples.', E'I believe that the economic benefits of tourism can outweigh its negative effects, but only when tourism is managed sustainably and responsibly.\n\nFirst, tourism generates significant revenue and employment opportunities for local communities. In many developing countries, tourism is one of the primary sources of foreign exchange earnings and jobs. For example, tourism in Thailand supports millions of jobs in hospitality, transportation, and local crafts, providing income for families who might otherwise have limited economic opportunities.\n\nSecond, tourism can incentivize the preservation of cultural heritage and natural environments. When communities recognize the economic value of their cultural sites and natural landscapes, they are more motivated to protect them. Many historical monuments and ecosystems have been preserved specifically because they attract tourists.\n\nHowever, unmanaged tourism can damage cultural authenticity and environmental sustainability. Overtourism in destinations like Barcelona and Venice has led to housing shortages for locals and degradation of historical sites. The carbon footprint of air travel also contributes significantly to climate change.\n\nThe key is balancing economic benefits with sustainable practices. This includes limiting visitor numbers, investing tourism revenue in community development, and promoting eco-friendly travel options.\n\nIn conclusion, with proper management and regulation, the economic benefits of tourism can indeed outweigh its negative effects on cultures and environments.', ARRAY['tourism', 'economic', 'benefits', 'culture', 'environment'], 15),
(3, 'Plastic Surgery', 'Do you think cosmetic surgery should be regulated more strictly? Give at least two reasons and support your opinion with examples.', E'I strongly believe that cosmetic surgery should be regulated more strictly to protect patients from harm.\n\nFirst, cosmetic surgery carries real medical risks including infection, nerve damage, and complications from anesthesia. Unregulated providers, particularly those offering cut-price procedures, often lack proper medical qualifications and facilities. High-profile cases of botched surgeries and patient deaths demonstrate the urgent need for stricter standards.\n\nSecond, aggressive marketing and social media influence have created unrealistic beauty standards that pressure vulnerable individuals, including teenagers, to undergo unnecessary procedures. Without regulation, commercial interests can override patient welfare, leading to a cycle of addiction to cosmetic procedures.\n\nThird, stricter regulation would ensure that only qualified medical professionals with appropriate training perform cosmetic procedures. This includes verifying credentials, mandating hospital privileges for high-risk procedures, and requiring detailed informed consent processes.\n\nWhile some argue that adults should have the freedom to modify their own bodies, this freedom should not come at the cost of safety. Proper regulation does not ban cosmetic surgery but ensures it is performed safely and ethically.\n\nIn conclusion, more stringent regulation of cosmetic surgery is essential to protect patient safety, prevent exploitation of vulnerable individuals, and ensure that qualified practitioners perform all procedures.', ARRAY['cosmetic surgery', 'regulation', 'safety', 'patients', 'risks'], 16),
(3, 'Fast Food', 'Do you think governments should impose higher taxes on fast food? Give at least two reasons and support your opinion with examples.', E'I believe that governments should consider imposing higher taxes on fast food to address public health concerns.\n\nFirst, higher fast food taxes can reduce consumption of unhealthy foods and improve public health outcomes. Similar to tobacco and alcohol taxes, price increases discourage consumption, particularly among price-sensitive groups such as young people and low-income families. Countries like Denmark have implemented fat taxes with some success in reducing purchases of unhealthy food products.\n\nSecond, tax revenue from fast food can be used to fund public health initiatives. Money raised from fast food taxes could be invested in nutrition education programs, subsidizing fresh fruits and vegetables for low-income families, or funding healthcare for diet-related diseases. This creates a virtuous cycle where unhealthy food consumption is reduced while healthy food becomes more accessible.\n\nThird, fast food taxes address the economic externality of healthcare costs. Diet-related diseases such as obesity, diabetes, and heart disease impose enormous costs on healthcare systems. By internalizing these costs through taxation, society can more fairly distribute the financial burden of poor dietary choices.\n\nCritics argue that fast food taxes disproportionately affect low-income households. However, well-designed tax policies can include exemptions for basic food items while targeting processed and unhealthy products.\n\nIn conclusion, higher taxes on fast food are a sensible public health measure that can reduce consumption, generate revenue for health initiatives, and address the broader costs of diet-related diseases.', ARRAY['fast food', 'taxes', 'health', 'public', 'consumption'], 17),
(3, 'Artificial Intelligence', 'Will artificial intelligence replace more jobs than it creates in the next decade? Give at least two reasons and support your opinion with examples.', E'I believe that artificial intelligence will create more jobs than it displaces in the next decade, though this transition will require significant workforce adaptation.\n\nFirst, AI typically automates specific tasks rather than entire occupations. While AI can efficiently perform repetitive and data-processing tasks, jobs that require creativity, emotional intelligence, complex problem-solving, and human interaction remain largely resistant to automation. For example, AI tools assist doctors in diagnosis but do not replace the compassion and judgment that healthcare professionals provide.\n\nSecond, AI creates entirely new industries and job categories that did not exist a decade ago. The rise of AI has generated demand for machine learning engineers, data scientists, AI ethicists, and prompt engineers. Furthermore, businesses deploying AI need human workers to manage, maintain, and improve these systems.\n\nThird, AI augments human capabilities rather than simply replacing them. In fields like customer service, legal research, and financial analysis, AI tools help workers become more productive and effective, allowing them to focus on higher-value activities.\n\nHowever, this optimistic outlook depends on investments in education and retraining. Workers in sectors most vulnerable to automation must have access to programs that help them develop new skills and transition to emerging roles.\n\nIn conclusion, while AI will undoubtedly disrupt certain job markets, it is more likely to create more jobs than it eliminates, provided societies invest adequately in workforce development.', ARRAY['artificial intelligence', 'jobs', 'automation', 'create', 'transition'], 18),
(3, 'Genetic Engineering', 'Do you support the use of genetic engineering to enhance human capabilities? Give at least two reasons and support your opinion with examples.', E'I do not support the use of genetic engineering to enhance human capabilities beyond treating diseases, and I will explain my reasons.\n\nFirst, genetic engineering for enhancement raises serious ethical concerns about fairness and equality. If genetic enhancements such as increased intelligence, strength, or longevity become available, they will likely be accessible only to wealthy families. This would create a genetically privileged class and widen social inequalities to unprecedented levels.\n\nSecond, the long-term consequences of genetic modifications in humans are unknown and potentially dangerous. Genetic traits often interact in complex ways that are not fully understood. Editing genes to enhance one trait might inadvertently create new health problems or have unintended effects on future generations.\n\nThird, human enhancement through genetic engineering could fundamentally alter what it means to be human. Our diversity, including perceived weaknesses, has shaped human culture, art, and empathy in profound ways. Deliberately engineering human traits risks losing the essential humanity that connects us all.\n\nHowever, genetic engineering to treat and prevent diseases is ethically acceptable because its purpose is to alleviate suffering rather than create advantages.\n\nIn conclusion, I oppose genetic engineering for human enhancement while supporting its use for medical treatment. We must establish clear ethical boundaries before pursuing capabilities that could divide humanity into the enhanced and the unenhanced.', ARRAY['genetic engineering', 'enhancement', 'ethics', 'equality', 'treatment'], 19),
(3, 'Universal Basic Income', 'Do you think governments should implement universal basic income for all citizens? Give at least two reasons and support your opinion with examples.', E'I believe that governments should seriously consider implementing universal basic income as a solution to growing economic insecurity.\n\nFirst, automation and artificial intelligence threaten to eliminate millions of jobs in coming decades, leaving many workers without income. Universal basic income can provide a financial floor that ensures everyone can meet basic needs regardless of employment status. This stability can prevent the social unrest and poverty that mass unemployment could cause.\n\nSecond, universal basic income empowers individuals to pursue education, entrepreneurship, and caregiving without fear of financial ruin. When people do not have to accept exploitative jobs simply to survive, they can make better career choices, start businesses, or care for family members. Several pilot programs in Finland and Canada have shown that recipients often become more productive and engaged in their communities.\n\nThird, universal basic income is simpler and more efficient than existing welfare bureaucracies. The administrative costs of means-tested programs are substantial, and many people who need assistance fall through the cracks of complex application processes.\n\nCritics worry that universal basic income would be prohibitively expensive and reduce incentives to work. However, funding mechanisms such as carbon taxes, wealth taxes on the super-rich, or savings from consolidating existing welfare programs could make it financially feasible.\n\nIn conclusion, universal basic income deserves serious consideration as a humane and efficient approach to addressing economic insecurity in the modern economy.', ARRAY['universal basic income', 'welfare', 'automation', 'security', 'opportunity'], 20);
